# Ambiente de Desenvolvimento

In [1]:
# !pip install -U langchain langchain-community langchain-core langchain-google-genai chromadb pypdf
# !pip install -U google-api-core google-api-python-client google-auth google-auth-httplib2 google-cloud-aiplatform google-cloud-bigquery google-cloud-core google-cloud-resource-manager google-cloud-storage google-crc32c google-genai google-generativeai
# !pip install pandas matplotlib seaborn scikit-learn scipy statsmodels plotly

In [2]:
import os
# from google.colab import userdata
import getpass
import kagglehub
import pandas as pd
import shutil

print("✅ Todas as bibliotecas do Agente foram importadas com sucesso!")
# Set API keys
def _set_env(var: str):
    if not os.environ.get(var):
        os.environ[var] = getpass.getpass(f"{var}: ")

_set_env("GEMINI_API_KEY_CHAT")
_set_env("GEMINI_API_KEY_CHAT_STREAM")
_set_env("TAVILY_API_KEY")

CHAVE_API_GOOGLE_CHAT = os.getenv("GEMINI_API_KEY_CHAT")
CHAVE_API_GOOGLE_CHAT_STREAM = os.getenv("GEMINI_API_KEY_CHAT_STREAM")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")

c:\Users\sirja\source\repos\mrjalves\Agentes\AGENTE_ITIL\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

✅ Todas as bibliotecas do Agente foram importadas com sucesso!

# Implementação de chat

In [3]:
from google import genai
from google.genai.types import Tool, GenerateContentConfig, GoogleSearch
from google.genai import types

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate
from langchain_classic.chains import create_retrieval_chain

from langchain_classic.chains.combine_documents import create_stuff_documents_chain

from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import Chroma
from typing import Literal
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_core.messages import ToolMessage,  HumanMessage, AIMessage, SystemMessage, BaseMessage
from langchain_core.runnables import RunnableConfig
from langgraph.graph.message import add_messages
from langchain_core.tools import tool
from typing import List, Dict, Optional
from typing import Annotated, Sequence, TypedDict, List
from langgraph.graph import StateGraph, END

from IPython.display import Image, display
from pydantic import BaseModel, Field
import json

C:\Users\sirja\AppData\Local\Temp\ipykernel_20216\573518875.py:11: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader

In [4]:
def definir_cliente(api_key: str):
   return genai.Client(api_key=api_key)

client_chat = definir_cliente(CHAVE_API_GOOGLE_CHAT)
client_stream = definir_cliente(CHAVE_API_GOOGLE_CHAT_STREAM)
client = client_chat

grounding_tool = types.Tool(
    google_search=types.GoogleSearch()
)

In [5]:
MODEL_ID = "gemini-2.5-flash" # @param ["gemini-3-flash-preview","gemini-2.5-flash-lite", "gemini-2.5-flash", "gemini-2.5-pro", "gemini-2.5-flash-preview", "gemini-3.1-pro-preview"] {"allow-input":true, isTemplate: true}
MODEL_ID_STREAM = "gemini-2.5-flash" # @param ["gemini-3-flash-preview","gemini-2.5-flash-lite", "gemini-2.5-flash", "gemini-2.5-pro", "gemini-2.5-flash-preview", "gemini-3.1-pro-preview"] {"allow-input":true, isTemplate: true}
topP = 0.95 # @param {type: "slider", min: 0, max: 1, step: 0.05}
temperature = 0.3 # @param {type: "slider", min: 0, max: 2, step: 0.05}
topK = 1
stop_sequence = ""

## Instrução do Sistema

In [6]:
instrucao = """
<role>
Você é um Especialista em ITIL 4 e um planejador estratégico com alto poder de raciocínio. 
Sua função é atuar como um consultor para Gestores de TI.
Você é incisivo, analítico e extremamente rigoroso na aplicação das diretrizes da ITIL 4. 
Seu objetivo é analisar bases de dados de tickets de TI e diagnosticar gargalos operacionais, recomendando as Práticas de Gerenciamento ITIL 4 exatas para resolvê-los.
</role>

<instructions>
Antes de gerar qualquer recomendação ao Gestor de TI, você deve agir de forma proativa, metódica e independentemente planejar e raciocinar sobre as seguintes etapas:

1) Dependências Lógicas e Alinhamento ITIL: Analise o conjunto de tickets contra os conceitos da ITIL 4.
    1.1) Categorização exata: Diferencie rigorosamente Incidentes (interrupções), Requisições de Serviço (pedidos padrão) e Problemas (causas raiz desconhecidas).
    1.2) Ordem de implementação: Garanta que a adoção de uma prática não exija outra como pré-requisito (ex: não recomendar 'Gerenciamento de Problemas' proativo sem que o 'Gerenciamento de Incidentes' esteja estabilizado).

2) Avaliação de Risco e Impacto no Negócio: Quais são as consequências do volume atual de tickets?
    2.1) Avalie o impacto da ausência das práticas ITIL 4 no valor entregue ao negócio. Priorize recomendações baseadas no risco operacional que os tickets representam.

3) Raciocínio Abdutivo e Causa Raiz: Para cada padrão de tickets encontrado, identifique a razão lógica mais provável para a falha sistêmica.
    3.1) Olhe além da causa imediata. Um alto volume de tickets de "reset de senha" pode não ser um problema de 'Central de Serviço' (Service Desk), mas sim uma falha no 'Gerenciamento de Acessos' ou necessidade de automação.
    3.2) Agrupe sintomas isolados para formar uma hipótese de deficiência em uma ou mais das 34 Práticas da ITIL 4.

4) Avaliação de Resultados (Validação): A prática recomendada realmente resolve o padrão identificado?
    4.1) Questione ativamente seu próprio plano inicial. Se a recomendação parece muito genérica, refine-a buscando o Princípio Orientador da ITIL 4 mais adequado (ex: "Otimizar e Automatizar").

5) Precisão e Embasamento (Grounding): Garanta que seu raciocínio seja tecnicamente impecável.
    5.1) Você DEVE utilizar a nomenclatura oficial da ITIL 4 (Sistema de Valor de Serviço, As 4 Dimensões, Práticas de Gerenciamento Geral/Serviço/Técnico). Não use jargões de TI genéricos quando houver um termo ITIL específico aplicável.
    5.2) Apenas recomende práticas que existam na ITIL 4. Se um padrão de tickets sugere a necessidade de uma prática que não está na ITIL 4, reformule sua recomendação para alinhar-se estritamente às práticas existentes.
    5.3) Se não houver um alinhamento claro entre o padrão de tickets e uma prática ITIL 4, seja transparente sobre isso e explique por que nenhuma prática se encaixa perfeitamente, em vez de forçar uma recomendação inadequada.
    5.4) Avalie se a pratica recomendada é a principal ou uma pratica de apoio para a solução do problema identificado.

6) Inibição de Resposta: Execute todo o raciocínio acima mentalmente antes de escrever a saída. Sua resposta final deve ser o resultado depurado desta análise.

<formatting_and_tone>
1 - Verbosidade: Mínima. Direto ao ponto.
2 - Respostas: Concisas, estruturadas e altamente acionáveis.
3 - Tonalidade: Técnica, executiva e consultiva.
4 - Estrutura obrigatória:
    - [Práticas ITIL 4 Recomendadas]: Um quadro com as praticas recomendadas, estruturadas como pratica principal e pratica auxiliar, com o ticket associado, em portugues br.
</formatting_and_tone>

<exemplos>
[INSERIR EXEMPLOS DE ENTRADA/SAÍDA AQUI]
</exemplos>
CONSIDERE EXEMPLOS DE AVALIAÇAÕ DE RESULTADOS PARA APRENDIZADO:
[
  {
    "Id": 3,
    "assunto": "Erro na Autocompletação",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Problemas",
    "Prática Principal - rag": "Gerenciamento de Problemas",
    "Prática Auxiliar - rag": "Gerenciamento de Capacidade e Desempenho",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 25,
    "assunto": "Problemas intermitentes",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Mudanças",
    "Prática Principal - rag": "Habilitação de Mudança",
    "Prática Auxiliar - rag": "Gerenciamento de Liberação",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 42,
    "assunto": "Pedido de Assistência pa",
    "Prática Principal": "Solicitação de Serviço",
    "Prática Auxiliar": "Gerenciamento de Nível de Serviço",
    "Prática Principal - rag": "Gerenciamento de Requisição de Serviço",
    "Prática Auxiliar - rag": "Gerenciamento de Catálogo de Serviço",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 57,
    "assunto": "Urgente: Relato de Falha",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Ativos de TI",
    "Prática Principal - rag": "Gerenciamento de Configuração de Serviço",
    "Prática Auxiliar - rag": "Gerenciamento de Ativos de TI",
    "avaliacao respostas - rag": "PARCIALMENTE"
  },
  {
    "Id": 62,
    "assunto": "Assistência Necessária pa",
    "Prática Principal": "Gerenciamento de Problemas",
    "Prática Auxiliar": "Gerenciamento de Mudanças",
    "Prática Principal - rag": "Gerenciamento de Configuração de Serviço",
    "Prática Auxiliar - rag": "Gerenciamento de Ativos de TI",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 77,
    "assunto": "Discrepância de Faturam",
    "Prática Principal": "Gerenciamento Financeiro",
    "Prática Auxiliar": "Gerenciamento de Incidentes",
    "Prática Principal - rag": "Gerenciamento Financeiro de Serviços",
    "Prática Auxiliar - rag": "Gerenciamento de Relacionamento",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 87,
    "assunto": "Urgente: Problema de In",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Disponibilidade",
    "Prática Principal - rag": "Gerenciamento de Disponibilidade",
    "Prática Auxiliar - rag": "Gerenciamento de Continuidade de Serviço",
    "avaliacao respostas - rag": "PARCIALMENTE"
  },
  {
    "Id": 98,
    "assunto": "Solicitação de Soluções d",
    "Prática Principal": "Solicitação de Serviço",
    "Prática Auxiliar": "Gerenciamento Financeiro",
    "Prática Principal - rag": "Gerenciamento Financeiro de Serviços",
    "Prática Auxiliar - rag": "Gerenciamento de Relacionamento",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 104,
    "assunto": "Interrupção do Roteador",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Problemas",
    "Prática Principal - rag": "Gerenciamento de Problemas",
    "Prática Auxiliar - rag": "Gerenciamento de Capacidade e Desempenho",
    "avaliacao respostas - rag": "PARCIALMENTE"
  },
  {
    "Id": 110,
    "assunto": "Urgente: Problemas de C",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Problemas",
    "Prática Principal - rag": "Gerenciamento de Problemas",
    "Prática Auxiliar - rag": "Gerenciamento de Capacidade e Desempenho",
    "avaliacao respostas - rag": "ACERTOU"
  }
]

<output_format>
Retorne APENAS texto formatado em Markdown, respeitando a estrutura definida em <formatting_and_tone>. Não inclua explicações sobre como você pensou; entregue apenas o resultado executivo final.
</output_format>
</instructions>

"""

## Funções Auxiliares

In [7]:
def construir_bloco_exemplos(exemplos_lista):
    """Gera o bloco XML interno de exemplos a partir dos gabaritos definidos."""
    xml_exemplos = ""
    
    for ex in exemplos_lista:
        # 1. Montando o input simulando a entrada do usuário/sistema
        ticket_info = f"Ticket: {ex.get('Ticket')}\nAssunto: {ex.get('Assunto')}\nDescrição: {ex.get('Descrição')}"
        
        # 2. Mapeando as respostas do gabarito
        diagnostico = ex.get("Solução", "Causa raiz mapeada no atendimento.")
        pratica_nome = ex.get('Prática ITIL que evitaria esse incidente e poderia resolver o problema previamente', '')
        praticas = f"- **{pratica_nome}**: Implementação necessária para prevenir reincidência." if pratica_nome else "- Não especificada"
        plano = "Revisar fluxo com as partes interessadas e ajustar o processo atual."

        exemplo_str = f"""  <exemplo>
    <input>
{ticket_info}
    </input>
    <output>
### [Diagnóstico]
{diagnostico}

### [Práticas ITIL 4 Recomendadas]
{praticas}

### [Plano de Ação]
{plano}
    </output>
  </exemplo>
"""
        xml_exemplos += exemplo_str
    
    return xml_exemplos

In [8]:


def obter_gabaritos_itil() -> List[Dict[str, str]]:
    """
    Retorna a lista completa de gabaritos de referência para análise ITIL.
    Ideal para ser usada como base de exemplos (Few-Shot) para o LLM.

    Retorna:
        Lista de dicionários, onde cada dicionário representa um ticket avaliado.
    """
    return [
        {
            "Ticket" :"1",
            "Assunto": "Lentidão na pesquisa do histórico de um cliente no CRM",
            "Descrição": "quando estou pesquisando o histórico do cliente Lojas Compra Mais, o CRM demora mais de 10 segundos para retornar os dados, o que inviabiliza o uso e parte das operações que preciso realizar diariamente.",
            "Solução": "sob a ótica da TI o tempo é condizente com a operação. Como não existe um objetivo ou métrica padrão definida para essa operação, entendemos que não existe problema com o serviço disponibilizado.",
            "Prática ITIL que evitaria esse incidente e poderia resolver o problema previamente": "Gerenciamento de Nível de Serviço e Gerenciamento de Disponibilidade",
        },
        {
            "Ticket" :"2",
            "Assunto": "Falha no processo de contato com leads no CRM",
            "Descrição": "no nosso processo comercial, após a segunda abordagem à um lead, precisamos nutri-lo com informações sobre nossos serviços, bem como enviar cases relacionados à sua atuação. Porém, no processo do CRM, após a segunda abordagem o lead é classificado como se não tivesse interesse nos nossos serviços. Isso vem causando uma dificuldade no nosso fluxo de atividades, poderiam realizar o ajuste?",
            "Solução": "infelizmente, alterar o processo do nosso CRM demandará um prazo e terá um custo (que será repassado para o orçamento da área comercial). Isso ocorre porque na reunião de definição que tivemos, embora ela tenha sido verbal e a análise realizada em nível macro, essa situação não foi destacada. Vamos solicitar os ajustes ao fornecedor do software.",
            "Prática ITIL que evitaria esse incidente e poderia resolver o problema previamente": "Análise de Negócio",
        },
        {
            "Ticket" :"3",
            "Assunto": "Indisponibilidade dos dashboards de BI quando acessados via navegador",
            "Descrição": "até ontem eu estava acessando normalmente meu conjunto de dashboards de BI chamado “Análises Financeiras”, porém, hoje pela manhã, ao tentar acessar pelo navegador retorna uma mensagem de indisponibilidade dos serviços de BI. Poderiam me ajudar?",
            "Solução": "o problema ocorreu porque ao instalarmos uma nova dll relacionada a uma atualização do software de CRM, gerou uma incompatibilidade com alguns serviços de BI, pois ambos os serviços (BI e CRM) compartilham o mesmo servidor de autenticação. Estamos voltando a versão do software de CRM e até o final do dia os serviços de BI devem estar disponíveis novamente.",
            "Prática ITIL que evitaria esse incidente e poderia resolver o problema previamente": "Controle de Mudanças",
        },
        {
            "Ticket" :"4",
            "Assunto": "levantamento de licenças",
            "Descrição": "preciso saber quantas licenças temos atualmente em uso do software Autocad 2025, pois vamos analisar a atualização das versões e precisamos identificar o custo total da demanda.",
            "Solução": "vamos fazer um levantamento (inventário) e retornamos esse chamado com a informações em 5 dias úteis",
            "Prática ITIL que evitaria esse incidente e poderia resolver o problema previamente": "Gerenciamento de Ativos de TI",
        },
        {
            "Ticket" :"5",
            "Assunto":"Qual foram os eventos que ocorreram simultaneamente quando o homem foi a lua?",
            "Descrição": "estou tentando entender quais foram os eventos que ocorreram simultaneamente quando o homem foi a lua.",
            "Solução": "essa pergunta não é relacionada a TI, portanto, não há recomendação de prática ITIL para esse case.",
            "Prática ITIL que evitaria esse incidente e poderia resolver o problema previamente": "Não há recomendação",
        }
    ]

def buscar_gabarito_por_id(ticket_id: str) -> Optional[Dict[str, str]]:
    """
    Busca um ticket específico dentro da lista de gabaritos.

    Args:
        ticket_id (str): O número do ticket desejado (ex: "3").

    Retorna:
        Um dicionário com os dados do ticket, ou None se não for encontrado.
    """
    gabaritos = obter_gabaritos_itil()

    for ticket in gabaritos:
        if ticket.get("Ticket") == str(ticket_id):
            return ticket

    print(f"AVISO: Ticket '{ticket_id}' não encontrado nos gabaritos.")
    return None

# # 1. Carregando todos os gabaritos (útil para injetar no prompt do LangChain)
# meus_gabaritos = obter_gabaritos_itil()
# print(f"Total de gabaritos carregados: {len(meus_gabaritos)}")

# # 2. Buscando um ticket específico de forma segura (sem usar o índice numérico da lista)
# ticket_alvo = buscar_gabarito_por_id("3")

# if ticket_alvo:
#     print("\n--- Dados do Ticket Encontrado ---")
#     print(f"Assunto: {ticket_alvo['Assunto']}")
#     print(f"Prática Recomendada: {ticket_alvo['Prática ITIL que evitaria esse incidente e poderia resolver o problema previamente']}")

## Prompt

In [9]:
def gerar_prompt_analise_itil(df: pd.DataFrame, idioma: str = 'pt', quantidade: int = 30) -> Optional[str]:
    """
    Filtra um DataFrame de tickets por idioma e monta um prompt em lote
    para análise do motor cognitivo baseada na ITIL 4.

    Args:
        df (pd.DataFrame): O DataFrame contendo os tickets consolidados.
        idioma (str): O idioma desejado para o filtro (ex: 'pt', 'en'). Padrão é 'pt'.
        quantidade (int): O número máximo de tickets no prompt. Padrão é 30.

    Returns:
        str: O texto final do prompt formatado, ou None se nenhum ticket for encontrado.
    """
    # 1. Filtra o DataFrame original para trazer apenas os tickets do idioma escolhido
    df_filtrado = df[df['idioma'] == idioma]

    # 2. Verifica se o filtro retornou resultados
    if df_filtrado.empty:
        print(f"AVISO: Nenhum ticket no idioma '{idioma}' foi encontrado no dataset.")
        return None

    # 3. Define a quantidade de tickets
    # Garantimos que não vamos pedir mais do que o total disponível
    limite = min(quantidade, len(df_filtrado))

    # 4. Início do Prompt (Cabeçalho único)
    prompt_texto = "Por favor, analise os seguintes tickets aplicando as diretrizes da ITIL 4 estabelecidas:\n"
    prompt_texto += "Para cada ticket, retorne apenas um quadro em Markdown com as colunas: Ticket ID, Prática Principal, Prática Auxiliar.\n"
    prompt_texto += "Se não houver recomendação para um ticket, preencha Prática Principal com 'Não há recomendação' e deixe Prática Auxiliar em branco.\n"
    prompt_texto += "---"

    # 5. Laço de repetição para percorrer o grupo de tickets
    for i in range(limite):
        ticket_atual = df_filtrado.iloc[i]

        # Adiciona as informações do ticket atual ao texto do prompt
        prompt_texto += f"""

Ticket #{ticket_atual['Id']}:
Assunto: {ticket_atual['assunto']}
Descricao: {ticket_atual['descricao']}
Solução: {ticket_atual['resposta']}
----------------------------------"""

    prompt_final = prompt_texto + "\nRetorne APENAS o quadro em Markdown. Não inclua explicações, plano de ação ou texto adicional."

    print(f"Sucesso! Prompt montado para um lote de {limite} tickets.")

    return prompt_final

In [10]:
def gerar_prompt_excluindo_primeiros(df: pd.DataFrame, excluir: int = 1, idioma: str = 'pt', quantidade: int = 30) -> Optional[str]:
    """
    Gera o prompt a partir do df excluindo os primeiros `excluir` registros.
    """
    if excluir < 0:
        raise ValueError("excluir deve ser >= 0")
    df_slice = df.iloc[excluir:]
    if df_slice.empty:
        print(f"AVISO: Não há tickets após excluir os primeiros {excluir} registros.")
        return None
    # reutiliza a função já definida no notebook
    return gerar_prompt_analise_itil(df_slice, idioma=idioma, quantidade=quantidade)

## Execução do chat

modo stream e modo normal

In [11]:
# Carrega o arquivo df_tickets.csv para um DataFrame
caminho_csv = "df_tickets.csv"

if not os.path.exists(caminho_csv):
    raise FileNotFoundError(f"Arquivo não encontrado: {caminho_csv}")

df_tickets = pd.read_csv(caminho_csv)

print("✅ df_tickets carregado com sucesso!")
print(f"Linhas: {df_tickets.shape[0]} | Colunas: {df_tickets.shape[1]}")
display(df_tickets.head())

✅ df_tickets carregado com sucesso!
Linhas: 22066 | Colunas: 9

,assunto,fila,descricao,tipo,resposta,prioridade,todas_tags,idioma,descricao_length
0,Problema crítico del servidor requiere atenció...,Technical Support,Es necesaria una investigación inmediata sobre...,Incident,Estamos investigando urgentemente el problema ...,high,"['Urgent Issue', 'Service Disruption', 'Incide...",es,149
1,Anfrage zur Verfügbarkeit des Dell XPS 13 9310,Customer Service,"Sehr geehrter Kundenservice,\n\nich hoffe, die...",Request,"Sehr geehrter <name>,\n\nvielen Dank, dass Sie...",low,"['Sales Inquiry', 'Product Support', 'Customer...",de,452
2,Erro na Autocompletação de Código do IntelliJ ...,Technical Support,"Prezado Suporte ao Cliente <name>,\n\nEstou es...",Incident,"Prezado <name>,\n\nObrigado por entrar em cont...",high,"['Technical Support', 'Software Bug', 'Problem...",pt,740
3,Urgent Assistance Required: AWS Service,IT Support,"Dear IT Services Support Team, \n\nI am reachi...",Request,"Dear <name>,\n\nThank you for reaching out reg...",high,"['IT Support', 'Urgent Issue', 'Service Notifi...",en,936
4,Problème d'affichage de MacBook Air,Product Support,Cher équipe de support du magasin en ligne Tec...,Incident,"Cher <name>,\n\nMerci de nous avoir contactés ...",low,"['Technical Support', 'Product Support', 'Hard...",fr,1322

In [12]:
df_tickets.insert(0, "Id", range(1, len(df_tickets) + 1))

display(df_tickets.head())

,Id,assunto,fila,descricao,tipo,resposta,prioridade,todas_tags,idioma,descricao_length
0,1,Problema crítico del servidor requiere atenció...,Technical Support,Es necesaria una investigación inmediata sobre...,Incident,Estamos investigando urgentemente el problema ...,high,"['Urgent Issue', 'Service Disruption', 'Incide...",es,149
1,2,Anfrage zur Verfügbarkeit des Dell XPS 13 9310,Customer Service,"Sehr geehrter Kundenservice,\n\nich hoffe, die...",Request,"Sehr geehrter <name>,\n\nvielen Dank, dass Sie...",low,"['Sales Inquiry', 'Product Support', 'Customer...",de,452
2,3,Erro na Autocompletação de Código do IntelliJ ...,Technical Support,"Prezado Suporte ao Cliente <name>,\n\nEstou es...",Incident,"Prezado <name>,\n\nObrigado por entrar em cont...",high,"['Technical Support', 'Software Bug', 'Problem...",pt,740
3,4,Urgent Assistance Required: AWS Service,IT Support,"Dear IT Services Support Team, \n\nI am reachi...",Request,"Dear <name>,\n\nThank you for reaching out reg...",high,"['IT Support', 'Urgent Issue', 'Service Notifi...",en,936
4,5,Problème d'affichage de MacBook Air,Product Support,Cher équipe de support du magasin en ligne Tec...,Incident,"Cher <name>,\n\nMerci de nous avoir contactés ...",low,"['Technical Support', 'Product Support', 'Hard...",fr,1322

In [13]:
prompt = gerar_prompt_analise_itil(df_tickets, idioma='pt', quantidade=30)
instrucao_final = instrucao.replace("[INSERIR EXEMPLOS DE ENTRADA/SAÍDA AQUI]", construir_bloco_exemplos(obter_gabaritos_itil()))

Sucesso! Prompt montado para um lote de 30 tickets.

In [14]:
print(instrucao_final)

<role>
Você é um Especialista em ITIL 4 e um planejador estratégico com alto poder de raciocínio.
Sua função é atuar como um consultor para Gestores de TI.
Você é incisivo, analítico e extremamente rigoroso na aplicação das diretrizes da ITIL 4.
Seu objetivo é analisar bases de dados de tickets de TI e diagnosticar gargalos operacionais, recomendando as Práticas de Gerenciamento ITIL 4 exatas para resolvê-los.
</role>

<instructions>
Antes de gerar qualquer recomendação ao Gestor de TI, você deve agir de forma proativa, metódica e independentemente planejar e raciocinar sobre as seguintes etapas:

1) Dependências Lógicas e Alinhamento ITIL: Analise o conjunto de tickets contra os conceitos da ITIL 4.
    1.1) Categorização exata: Diferencie rigorosamente Incidentes (interrupções), Requisições de Serviço (pedidos padrão) e Problemas (causas raiz desconhecidas).
    1.2) Ordem de implementação: Garanta que a adoção de uma prática não exija outra como pré-requisito (ex: não recomendar 'Gerenciamento de Problemas' proativo sem que o 'Gerenciamento de Incidentes' esteja estabilizado).

2) Avaliação de Risco e Impacto no Negócio: Quais são as consequências do volume atual de tickets?
    2.1) Avalie o impacto da ausência das práticas ITIL 4 no valor entregue ao negócio. Priorize recomendações baseadas no risco operacional que os tickets representam.

3) Raciocínio Abdutivo e Causa Raiz: Para cada padrão de tickets encontrado, identifique a razão lógica mais provável para a falha sistêmica.
    3.1) Olhe além da causa imediata. Um alto volume de tickets de "reset de senha" pode não ser um problema de 'Central de Serviço' (Service Desk), mas sim uma falha no 'Gerenciamento de Acessos' ou necessidade de automação.
    3.2) Agrupe sintomas isolados para formar uma hipótese de deficiência em uma ou mais das 34 Práticas da ITIL 4.

4) Avaliação de Resultados (Validação): A prática recomendada realmente resolve o padrão identificado?
    4.1) Questione ativamente seu próprio plano inicial. Se a recomendação parece muito genérica, refine-a buscando o Princípio Orientador da ITIL 4 mais adequado (ex: "Otimizar e Automatizar").

5) Precisão e Embasamento (Grounding): Garanta que seu raciocínio seja tecnicamente impecável.
    5.1) Você DEVE utilizar a nomenclatura oficial da ITIL 4 (Sistema de Valor de Serviço, As 4 Dimensões, Práticas de Gerenciamento Geral/Serviço/Técnico). Não use jargões de TI genéricos quando houver um termo ITIL específico aplicável.
    5.2) Apenas recomende práticas que existam na ITIL 4. Se um padrão de tickets sugere a necessidade de uma prática que não está na ITIL 4, reformule sua recomendação para alinhar-se estritamente às práticas existentes.
    5.3) Se não houver um alinhamento claro entre o padrão de tickets e uma prática ITIL 4, seja transparente sobre isso e explique por que nenhuma prática se encaixa perfeitamente, em vez de forçar uma recomendação inadequada.
    5.4) Avalie se a pratica recomendada é a principal ou uma pratica de apoio para a solução do problema identificado.

6) Inibição de Resposta: Execute todo o raciocínio acima mentalmente antes de escrever a saída. Sua resposta final deve ser o resultado depurado desta análise.

<formatting_and_tone>
1 - Verbosidade: Mínima. Direto ao ponto.
2 - Respostas: Concisas, estruturadas e altamente acionáveis.
3 - Tonalidade: Técnica, executiva e consultiva.
4 - Estrutura obrigatória:
    - [Práticas ITIL 4 Recomendadas]: Um quadro com as praticas recomendadas, estruturadas como pratica principal e pratica auxiliar, com o ticket associado, em portugues br.
</formatting_and_tone>

<exemplos>
  <exemplo>
    <input>
Ticket: 1
Assunto: Lentidão na pesquisa do histórico de um cliente no CRM
Descrição: quando estou pesquisando o histórico do cliente Lojas Compra Mais, o CRM demora mais de 10 segundos para retornar os dados, o que inviabiliza o uso e parte das operações que preciso realizar diariamente.
    </input>
    <output>
### [Diagnóstico]
sob a ótica da TI o tempo é condizente com a operação. Como não existe um objetivo ou métrica padrão definida para essa operação, entendemos que não existe problema com o serviço disponibilizado.

### [Práticas ITIL 4 Recomendadas]
- **Gerenciamento de Nível de Serviço e Gerenciamento de Disponibilidade**: Implementação necessária para prevenir reincidência.

### [Plano de Ação]
Revisar fluxo com as partes interessadas e ajustar o processo atual.
    </output>
  </exemplo>
  <exemplo>
    <input>
Ticket: 2
Assunto: Falha no processo de contato com leads no CRM
Descrição: no nosso processo comercial, após a segunda abordagem à um lead, precisamos nutri-lo com informações sobre nossos serviços, bem como enviar cases relacionados à sua atuação. Porém, no processo do CRM, após a segunda abordagem o lead é classificado como se não tivesse interesse nos nossos serviços. Isso vem causando uma dificuldade no nosso fluxo de atividades, poderiam realizar o ajuste?
    </input>
    <output>
### [Diagnóstico]
infelizmente, alterar o processo do nosso CRM demandará um prazo e terá um custo (que será repassado para o orçamento da área comercial). Isso ocorre porque na reunião de definição que tivemos, embora ela tenha sido verbal e a análise realizada em nível macro, essa situação não foi destacada. Vamos solicitar os ajustes ao fornecedor do software.

### [Práticas ITIL 4 Recomendadas]
- **Análise de Negócio**: Implementação necessária para prevenir reincidência.

### [Plano de Ação]
Revisar fluxo com as partes interessadas e ajustar o processo atual.
    </output>
  </exemplo>
  <exemplo>
    <input>
Ticket: 3
Assunto: Indisponibilidade dos dashboards de BI quando acessados via navegador
Descrição: até ontem eu estava acessando normalmente meu conjunto de dashboards de BI chamado “Análises Financeiras”, porém, hoje pela manhã, ao tentar acessar pelo navegador retorna uma mensagem de indisponibilidade dos serviços de BI. Poderiam me ajudar?
    </input>
    <output>
### [Diagnóstico]
o problema ocorreu porque ao instalarmos uma nova dll relacionada a uma atualização do software de CRM, gerou uma incompatibilidade com alguns serviços de BI, pois ambos os serviços (BI e CRM) compartilham o mesmo servidor de autenticação. Estamos voltando a versão do software de CRM e até o final do dia os serviços de BI devem estar disponíveis novamente.

### [Práticas ITIL 4 Recomendadas]
- **Controle de Mudanças**: Implementação necessária para prevenir reincidência.

### [Plano de Ação]
Revisar fluxo com as partes interessadas e ajustar o processo atual.
    </output>
  </exemplo>
  <exemplo>
    <input>
Ticket: 4
Assunto: levantamento de licenças
Descrição: preciso saber quantas licenças temos atualmente em uso do software Autocad 2025, pois vamos analisar a atualização das versões e precisamos identificar o custo total da demanda.
    </input>
    <output>
### [Diagnóstico]
vamos fazer um levantamento (inventário) e retornamos esse chamado com a informações em 5 dias úteis

### [Práticas ITIL 4 Recomendadas]
- **Gerenciamento de Ativos de TI**: Implementação necessária para prevenir reincidência.

### [Plano de Ação]
Revisar fluxo com as partes interessadas e ajustar o processo atual.
    </output>
  </exemplo>
  <exemplo>
    <input>
Ticket: 5
Assunto: Qual foram os eventos que ocorreram simultaneamente quando o homem foi a lua?
Descrição: estou tentando entender quais foram os eventos que ocorreram simultaneamente quando o homem foi a lua.
    </input>
    <output>
### [Diagnóstico]
essa pergunta não é relacionada a TI, portanto, não há recomendação de prática ITIL para esse case.

### [Práticas ITIL 4 Recomendadas]
- **Não há recomendação**: Implementação necessária para prevenir reincidência.

### [Plano de Ação]
Revisar fluxo com as partes interessadas e ajustar o processo atual.
    </output>
  </exemplo>

</exemplos>
CONSIDERE EXEMPLOS DE AVALIAÇAÕ DE RESULTADOS PARA APRENDIZADO:
[
  {
    "Id": 3,
    "assunto": "Erro na Autocompletação",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Problemas",
    "Prática Principal - rag": "Gerenciamento de Problemas",
    "Prática Auxiliar - rag": "Gerenciamento de Capacidade e Desempenho",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 25,
    "assunto": "Problemas intermitentes",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Mudanças",
    "Prática Principal - rag": "Habilitação de Mudança",
    "Prática Auxiliar - rag": "Gerenciamento de Liberação",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 42,
    "assunto": "Pedido de Assistência pa",
    "Prática Principal": "Solicitação de Serviço",
    "Prática Auxiliar": "Gerenciamento de Nível de Serviço",
    "Prática Principal - rag": "Gerenciamento de Requisição de Serviço",
    "Prática Auxiliar - rag": "Gerenciamento de Catálogo de Serviço",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 57,
    "assunto": "Urgente: Relato de Falha",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Ativos de TI",
    "Prática Principal - rag": "Gerenciamento de Configuração de Serviço",
    "Prática Auxiliar - rag": "Gerenciamento de Ativos de TI",
    "avaliacao respostas - rag": "PARCIALMENTE"
  },
  {
    "Id": 62,
    "assunto": "Assistência Necessária pa",
    "Prática Principal": "Gerenciamento de Problemas",
    "Prática Auxiliar": "Gerenciamento de Mudanças",
    "Prática Principal - rag": "Gerenciamento de Configuração de Serviço",
    "Prática Auxiliar - rag": "Gerenciamento de Ativos de TI",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 77,
    "assunto": "Discrepância de Faturam",
    "Prática Principal": "Gerenciamento Financeiro",
    "Prática Auxiliar": "Gerenciamento de Incidentes",
    "Prática Principal - rag": "Gerenciamento Financeiro de Serviços",
    "Prática Auxiliar - rag": "Gerenciamento de Relacionamento",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 87,
    "assunto": "Urgente: Problema de In",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Disponibilidade",
    "Prática Principal - rag": "Gerenciamento de Disponibilidade",
    "Prática Auxiliar - rag": "Gerenciamento de Continuidade de Serviço",
    "avaliacao respostas - rag": "PARCIALMENTE"
  },
  {
    "Id": 98,
    "assunto": "Solicitação de Soluções d",
    "Prática Principal": "Solicitação de Serviço",
    "Prática Auxiliar": "Gerenciamento Financeiro",
    "Prática Principal - rag": "Gerenciamento Financeiro de Serviços",
    "Prática Auxiliar - rag": "Gerenciamento de Relacionamento",
    "avaliacao respostas - rag": "ERROU"
  },
  {
    "Id": 104,
    "assunto": "Interrupção do Roteador",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Problemas",
    "Prática Principal - rag": "Gerenciamento de Problemas",
    "Prática Auxiliar - rag": "Gerenciamento de Capacidade e Desempenho",
    "avaliacao respostas - rag": "PARCIALMENTE"
  },
  {
    "Id": 110,
    "assunto": "Urgente: Problemas de C",
    "Prática Principal": "Gerenciamento de Incidentes",
    "Prática Auxiliar": "Gerenciamento de Problemas",
    "Prática Principal - rag": "Gerenciamento de Problemas",
    "Prática Auxiliar - rag": "Gerenciamento de Capacidade e Desempenho",
    "avaliacao respostas - rag": "ACERTOU"
  }
]

<output_format>
Retorne APENAS texto formatado em Markdown, respeitando a estrutura definida em <formatting_and_tone>. Não inclua explicações sobre como você pensou; entregue apenas o resultado executivo final.
</output_format>
</instructions>

In [15]:
print(prompt)

Por favor, analise os seguintes tickets aplicando as diretrizes da ITIL 4 estabelecidas:
Para cada ticket, retorne apenas um quadro em Markdown com as colunas: Ticket ID, Prática Principal, Prática Auxiliar.
Se não houver recomendação para um ticket, preencha Prática Principal com 'Não há recomendação' e deixe Prática Auxiliar em branco.
---

Ticket #3:
Assunto: Erro na Autocompletação de Código do IntelliJ IDEA
Descricao: Prezado Suporte ao Cliente <name>,

Estou escrevendo para trazer à sua atenção um problema recorrente com o recurso de autocompletação de código no IntelliJ IDEA 2024.1. Este problema específico faz com que o aplicativo travar frequentemente durante o desenvolvimento, o que está prejudicando significativamente minha produtividade. Cada vez que tento usar o recurso de autocompletação de código, o software fica sem resposta, levando eventualmente a um travamento. Já tentei os passos comuns de solução de problemas, como reinstalação e aplicação das atualizações mais recentes, mas o problema persiste. Agradeceria sua orientação sobre como resolver esse problema o mais rápido possível. Obrigado pela sua atenção.

Atenciosamente,
<name>
Solução: Prezado <name>,

Obrigado por entrar em contato e nos informar sobre o problema com o recurso de autocompletação de código no IntelliJ IDEA 2024.1. Entendemos o quão crucial essa ferramenta é para o seu trabalho de desenvolvimento.

Para ajudá-lo melhor, por favor, tente os seguintes passos:
1. Verifique a compatibilidade do seu sistema com o IntelliJ IDEA 2024.1.
2. Limpe o cache da IDE acessando Arquivo > Invalidar Caches / Reiniciar.
3. Desative quaisquer plugins desnecessários para ver se estão causando conflitos.
4. Aumente a alocação de memória para o aplicativo por meio das opções de VM.

Se o problema persistir, por favor, nos envie os logs (localizados em Ajuda > Coletar Logs) para uma análise mais profunda. Estamos comprometidos em resolver esse problema o mais rápido possível.

Atenciosamente,
Equipe de Suporte ao Cliente
----------------------------------

Ticket #25:
Assunto: Problemas intermitentes de exibição após atualização de firmware
Descricao: Caro Suporte ao Cliente,

 Estou entrando em contato para relatar um problema com meu Samsung QLED QN90A que comprei em sua loja. Após a recente atualização de firmware, estou enfrentando problemas intermitentes de exibição. A tela às vezes pisca e às vezes perde o sinal completamente, o que prejudica significativamente minha experiência de visualização.

 Esses problemas começaram a ocorrer imediatamente após a atualização de firmware, sugerindo uma possível causa. Tentei solucionar o problema verificando todas as conexões e reiniciando a TV para as configurações de fábrica, mas o problema persiste.

 Você poderia me fornecer orientações sobre como resolver isso ou me informar os próximos passos? Se um retrocesso de firmware ou uma correção estiver disponível, isso seria extremamente útil para recuperar a funcionalidade total da minha TV.

 Obrigado antecipadamente pela sua assistência. Aguardo uma solução rápida.

 Atenciosamente,

 <name>
 <email>
 <tel_num>
Solução: Caro <name>,

 Obrigado por entrar em contato e pela sua paciência. Lamentamos saber sobre os problemas de exibição após a atualização de firmware em sua Samsung QLED QN90A.

 Para resolver isso, por favor, assegure-se de que o software da sua TV esteja atualizado com os últimos patches do site de suporte da Samsung. Se o problema persistir, recomendamos um retrocesso de firmware, se disponível, com o qual podemos ajudá-lo. Além disso, nosso centro de serviços pode diagnosticar e resolver o problema, se necessário.

 Entre em contato conosco pelo <tel_num> ou visite o centro de serviços mais próximo com o comprovante de compra. Pedimos desculpas pelo inconveniente e estamos comprometidos em resolver isso rapidamente.

 Atenciosamente,

 Equipe de Suporte ao Cliente
----------------------------------

Ticket #42:
Assunto: Pedido de Assistência para Administração de Servidores
Descricao: Prezado Suporte ao Cliente de Serviços de TI,

Espero que esta mensagem o encontre bem. Estou escrevendo para solicitar assistência adicional com a administração do servidor para melhorar a eficiência e o desempenho de nossos sistemas atuais. Acreditamos que aproveitar seus serviços de consultoria pode nos ajudar a alcançar essas melhorias e abordar quaisquer desafios existentes que estamos enfrentando.

Nosso principal objetivo é otimizar as operações do servidor para apoiar nosso crescimento e garantir a confiabilidade de nossa infraestrutura de TI. Após revisar seus Serviços de Consultoria de TI, estamos confiantes de que a experiência de sua equipe pode fornecer insights e soluções valiosas adaptadas às nossas necessidades específicas.

Poderíamos, por favor, agendar uma consulta com um de seus especialistas na sua primeira conveniência? Estamos ansiosos para discutir estratégias potenciais, planos de serviço e quaisquer recomendações que você possa ter. Aguardamos ansiosamente o refinamento de nossos sistemas e a sua adaptação às melhores práticas.

Obrigado pela sua atenção a este pedido. Agradecemos sua assistência e estamos animados com a possibilidade de colaborar com sua equipe.

Atenciosamente,

<name>
<position>
<company>
<tel_num>
<email>
Solução: Prezado <name>,

Obrigado por entrar em contato com o Suporte ao Cliente de Serviços de TI. Agradecemos seu interesse em nossos serviços de consultoria para melhorar a administração do seu servidor.

Ficaríamos felizes em agendar uma consulta para você com um de nossos especialistas. Por favor, nos informe sua disponibilidade e organizaremos uma reunião na primeira conveniência.

Nossa equipe está animada para colaborar com você, discutir estratégias potenciais e fornecer soluções personalizadas para otimizar suas operações de servidor e apoiar seu crescimento.

Aguardamos ansiosos para trabalhar com você.

Atenciosamente,

Equipe de Suporte ao Cliente de Serviços de TI
----------------------------------

Ticket #57:
Assunto: Urgente: Relato de Falha na Bateria do MacBook Air M1 Adquirido na Loja Virtual
Descricao: Prezado Atendimento ao Cliente,<br><br>Recentemente adquiri um MacBook Air M1 em sua loja virtual e estou enfrentando sérios problemas com a bateria. Ela se esgota de forma extremamente rápida. Por favor, me avisem sobre os passos que devo seguir para realizar uma substituição ou um conserto.<br><br>Atenciosamente,<br><nome>
Solução: Prezado [Nome],<br><br>Lamento pelo inconveniente. Por gentileza, inicie verificando a condição da bateria nas Preferências do Sistema > Bateria. Se os problemas continuarem, contate nossa equipe de suporte pelo [número de suporte] ou siga as diretrizes em nosso site para obter uma substituição ou conserto.<br><br>Cordialmente,<br>Atendimento ao Cliente
----------------------------------

Ticket #62:
Assunto: Assistência Necessária para Integração do Jira Software
Descricao: Prezado Time de Suporte ao Cliente,

Espero que esta mensagem o encontre bem. Estou entrando em contato a respeito de um ticket que diz respeito a problemas que temos encontrado com nossas configurações de quadro Scrum na versão 8.20 do Jira Software. Temos enfrentado dificuldades consideráveis para integrar nossos fluxos de gerenciamento de projetos de maneira suave. Apesar de nossos esforços para configurar os quadros de acordo com nossos requisitos, certas funções não parecem funcionar como esperado. Isso interrompeu nosso fluxo de trabalho, afetando a produtividade.

Estamos buscando seu aconselhamento especializado para nos ajudar a resolver esse problema. Especificamente, precisamos de orientação sobre configurações ideais para uma integração de gerenciamento de projetos sem fricções. Se possível, eu apreciaria um guia passo a passo ou recomendações sobre as melhores práticas para garantir que nossa configuração esteja perfeitamente alinhada com os recursos mais recentes no Jira Software 8.20.

Obrigado pela sua atenção a este assunto, e aguardo sua resposta rápida.

Atenciosamente,
<name>
Solução: Prezado <name>,

Obrigado por entrar em contato sobre as dificuldades que você está enfrentando com a configuração do seu quadro Scrum na versão 8.20 do Jira Software. Entendo o quão crucial é uma integração suave para manter a produtividade da sua equipe.

Para ajudá-lo de forma eficaz, recomendo começar com os seguintes passos para uma configuração ideal:

1. Revisar Filtros do Quadro: Certifique-se de que os filtros do seu quadro estão configurados corretamente para refletir os problemas que você deseja exibir. Consultas JQL incorretas podem resultar em itens faltando.

2. Validar Esquemas de Fluxo de Trabalho: Verifique se seus fluxos de trabalho correspondem corretamente a cada projeto e tipo de problema. Transições mal configuradas podem levar a comportamentos inesperados.

3. Verificação de Permissões: Garanta que os membros da equipe tenham as permissões necessárias para acesso ao quadro e tarefas para evitar problemas de acesso que causam interrupções.

4. Verifique Conflitos de Plugins: Revise quaisquer plugins de terceiros que possam interferir na funcionalidade padrão. Desativá-los temporariamente pode ajudar a diagnosticar o problema.

5. Melhorias Específicas da Versão: Aproveite os novos recursos na versão 8.20 revisando as notas de lançamento da Atlassian para uso ideal e alinhamento.

6. Ajustes de Desempenho: Otimize o desempenho do quadro minimizando atualizações rápidas do quadro e mantendo um tamanho de backlog gerenciável.

Se esses passos não resolverem seus problemas, por favor, forneça mensagens de erro específicas ou comportamentos que você está encontrando, e ofereceremos suporte mais direcionado.

Sinta-se à vontade para entrar em contato se precisar de mais assistência. Nossa equipe está aqui para ajudar a garantir que sua configuração do Jira Software apoie sua produtividade sem interrupções.

Atenciosamente,

Equipe de Suporte ao Cliente
----------------------------------

Ticket #77:
Assunto: Discrepância de Faturamento no Google Workspace
Descricao: Caro Time de Suporte de TI,

Estou escrevendo para relatar um valor de faturamento incorreto na minha assinatura do Google Workspace Business Standard sob a conta <acc_num>. Por favor, revise e ajuste a fatura. Aguardando sua pronta resposta.

Atenciosamente,

<name>
Solução: Caro <name>,

Obrigado por entrar em contato. Revisaremos os detalhes de faturamento da sua assinatura do Google Workspace Business Standard sob a conta <acc_num>. Nossa equipe investigará a discrepância e fará os ajustes necessários. Atualizaremos você o mais rápido possível com uma solução.

Atenciosamente,
Time de Suporte de TI
----------------------------------

Ticket #87:
Assunto: Urgente: Problema de inatividade do Serviço de Gerenciamento da AWS
Descricao: Prezado time de suporte ao cliente,

Estou escrevendo para informar sobre um problema com seu Serviço de Gerenciamento da AWS, que recentemente enfrentou inatividade não planejada. Essa interrupção impactou significativamente o acesso dos clientes ao servidor virtual. Precisamos de assistência imediata para resolver o problema e garantir que não ocorram mais interrupções. Por favor, priorize a restauração da funcionalidade e mantenha-nos atualizados sobre seu progresso. Dependemos muito do seu serviço, e tais incidentes afetam criticamente nossas operações. Ação rápida seria apreciada. Entre em contato comigo pelo <tel_num> para mais discussões.

Obrigado,

<name>
Solução: Prezado <name>,

Obrigado por entrar em contato. Pedimos desculpas pelo inconveniente causado pela inatividade não planejada de nosso Serviço de Gerenciamento da AWS. Entendemos o impacto crítico em suas operações e estamos atualmente trabalhando para resolver o problema. Fique tranquilo, nossa equipe está priorizando a restauração da funcionalidade total do serviço. Manteremos você atualizado sobre nosso progresso e ações tomadas. Para mais discussões, por favor, aguarde uma ligação direta em breve.

Obrigado pela sua paciência e compreensão.

Atenciosamente,
Equipe do Service Desk
----------------------------------

Ticket #98:
Assunto: Solicitação de Soluções de Gerenciamento da AWS Eficientes em Custo
Descricao: Caro Time de Suporte ao Cliente,

Espero que esta mensagem os encontre bem. Meu nome é <name> e atualmente estou supervisionando as operações no escritório de <name>. Temos utilizado seus Serviços de Gerenciamento da AWS no último ano e, embora o serviço tenha sido satisfatório, encontramos alguns desafios em relação aos altos custos operacionais associados a ele.

À luz dessas restrições financeiras, estamos buscando aconselhamento sobre como otimizar da melhor forma nossos Serviços de Gerenciamento da AWS existentes. Especificamente, estamos interessados em explorar soluções que sejam eficientes em custo e que possam ajudar a racionalizar nossas operações sem comprometer o desempenho ou a confiabilidade. Poderiam, por favor, nos fornecer insights ou recomendações sobre opções ou ajustes disponíveis que podemos considerar?

Compreender os detalhes do nosso uso da AWS e identificar áreas potenciais para economia de custos pode beneficiar muito nosso planejamento financeiro e estratégia operacional.

Muito obrigado pela sua assistência e por considerar nossa solicitação. Aguardo seu retorno em breve sobre possíveis soluções ou para agendar uma reunião com um consultor.

Atenciosamente,

<name>
Departamento de TI de <name>
Contato: <tel_num>
Solução: Caro <name>,

Obrigado por entrar em contato conosco sobre suas preocupações em relação aos custos dos Serviços de Gerenciamento da AWS. Estamos felizes em saber que você considera nossos serviços satisfatórios e estamos aqui para ajudá-lo a explorar opções para torná-los mais eficientes em custo.

Para atender às suas necessidades, recomendamos os seguintes passos iniciais:

1. **AWS Cost Explorer e Dashboard de Faturamento**: Utilize essas ferramentas para obter insights detalhados sobre seus padrões de gastos e identificar serviços que estão consumindo mais recursos.

2. **Dimensionamento Adequado**: Assegure-se de que os recursos que você provisionou correspondam ao seu uso atual. Às vezes, reduzir ou mudar para famílias de instâncias mais novas e menos caras pode reduzir significativamente os custos.

3. **Instâncias Reservadas e Planos de Economia**: Avalie se comprometer-se com instâncias reservadas ou participar de planos de economia pode beneficiar você para serviços que têm uso estável e previsível.

4. **Auto Scaling**: Implemente auto-scaling onde aplicável para garantir que você pague apenas pelo que utilizar, escalando para baixo durante horários de pico e reduzindo quando não estiver em demanda.

5. **Otimizar Transferências de Dados**: Revise suas despesas de transferência de dados para ver se existem estratégias mais econômicas que você pode aplicar, como cache ou implantação de conteúdo por meio de Redes de Entrega de Conteúdo, como o Amazon CloudFront.

6. **Consulta**: Podemos agendar uma reunião com um de nossos consultores de otimização em nuvem que pode fornecer insights mais personalizados sobre seu uso atual.

Por favor, nos informe um horário conveniente para você discutir mais suas oportunidades. Estamos comprometidos em ajudá-lo a encontrar as melhores soluções para reduzir seus custos sem sacrificar desempenho ou confiabilidade.

Aguardamos ansiosamente para ajudá-lo mais.

Atenciosamente,

Equipe do Service Desk
----------------------------------

Ticket #104:
Assunto: Interrupção do Roteador Cisco
Descricao: Caro Suporte ao Cliente,

Estou escrevendo para informá-los sobre um problema técnico de alta prioridade que estamos enfrentando com o Roteador Cisco ISR4331. O erro associado a este equipamento levou a uma interrupção total do serviço que afeta vários clientes, necessitando de atenção e resolução imediatas.

Este problema foi detectado pela primeira vez em <date>, e impactou severamente nossa entrega de serviços. Recebemos inúmeros relatórios de clientes que não conseguem acessar seus serviços, e isso está causando grandes interrupções operacionais para eles. Parece que o roteador é incapaz de manter a conectividade e essa interrupção é consistente em várias redes conectadas. Verificamos todas as conexões e configurações para garantir que o problema não está em nossos sistemas internos. Consequentemente, suspeitamos fortemente de uma falha originada no hardware ou firmware do roteador que precisa de uma investigação urgente.

Dada a natureza crítica deste problema, estamos escalando isso para a mais alta prioridade. Nossos clientes dependem de nós para um serviço confiável, e é imperativo que essa interrupção seja resolvida rapidamente para minimizar perdas adicionais e restaurar a confiança dos afetados. Agradeceríamos se vocês pudessem despachar uma equipe técnica sênior para avaliar e tratar a causa raiz o mais cedo possível.

Vocês poderiam, por favor, confirmar o recebimento desta comunicação e fornecer orientações sobre os próximos passos? Confiamos em sua proficiência e contamos com sua experiência para nos ajudar a restaurar a funcionalidade total o mais rápido possível.

Para fins de documentação, nosso número da conta é <acc_num>. Por favor, entre em contato conosco por este e-mail ou pelo <tel_num> caso necessitem de mais informações ou esclarecimentos.

Obrigado pela sua atenção rápida a este problema crítico.

Atenciosamente,

<name>
Equipe de Serviços de TI
Solução: Caro <name>,

Obrigado por entrar em contato e nos informar sobre o problema crítico com o Roteador Cisco ISR4331. Entendemos a urgência e o impacto que essa interrupção está causando em seus serviços e clientes.

Nossa equipe técnica está priorizando seu caso e irá coordenar com vocês em breve para tratar a falha suspeita de hardware ou firmware. Recomendamos preparar quaisquer logs ou dados relevantes que possam ajudar em um diagnóstico e resolução rápidos.

Por favor, aguarde um membro da equipe técnica sênior entrando em contato dentro da próxima hora para começar a resolver este problema. Nosso objetivo é restaurar a funcionalidade total e manteremos vocês atualizados ao longo do processo.

Obrigado pela sua paciência e confiança em nossos serviços. Estamos comprometidos em resolver esta questão com a máxima urgência.

Atenciosamente,

[Seu Nome]
Equipe de Suporte ao Cliente
----------------------------------

Ticket #110:
Assunto: Urgente: Problemas de Conectividade de Rede do Roteador Cisco ISR4331
Descricao: Caro Time de Suporte ao Cliente,

Espero que esta mensagem o encontre bem. Estou escrevendo para trazer formalmente à sua atenção um problema relacionado à conectividade de rede do meu Roteador Cisco ISR4331. Meu nome é <name>, e venho enfrentando problemas de forma consistente nas últimas semanas. O dispositivo, que me foi recomendado por seu desempenho de alta reputação, infelizmente, não está entregando o que era esperado.

O problema principal é que o roteador falha em manter uma velocidade de rede consistente e frequentemente desconecta. Isso interrompeu significativamente meus arranjos de trabalho em casa, onde uma conectividade de internet confiável é crucial. Inicialmente, pensei que isso poderia estar relacionado ao meu provedor de serviços de internet, mas após diversas verificações e consultas com eles, foi confirmado que o problema não é do lado deles.

Para fornecer mais detalhes, a conexão parece cair de forma imprevisível, às vezes até várias vezes na mesma hora, e nesse momentos, nenhuma atividade específica está sendo realizada que poderia sobrecarregar a rede. Já tentei etapas básicas de solução de problemas, como reiniciar o roteador, redefini-lo para as configurações de fábrica e atualizar o firmware. Nenhuma dessas medidas trouxe um resultado positivo.


In [16]:
modelos_disponiveis = [
    "gemini-3-flash-preview",
    "gemini-2.5-flash-lite",
    "gemini-2.5-flash",
    "gemini-2.5-pro",
    "gemini-2.5-flash-preview",
    "gemini-3.1-pro-preview",
    "gemini-3.1-flash-lite-preview"
]

print("Modelos disponíveis:")
for i, modelo in enumerate(modelos_disponiveis, start=1):
    print(f"{i}. {modelo}")

escolha = input(f"Selecione o modelo [1-{len(modelos_disponiveis)}] ou digite o nome exato (Enter mantém '{MODEL_ID}'): ").strip()

if escolha:
    if escolha.isdigit() and 1 <= int(escolha) <= len(modelos_disponiveis):
        MODEL_ID = modelos_disponiveis[int(escolha) - 1]
    elif escolha in modelos_disponiveis:
        MODEL_ID = escolha
    else:
        raise ValueError("Modelo inválido.")

escolha_stream = input(f"Selecione o modelo de stream [1-{len(modelos_disponiveis)}] ou digite o nome exato (Enter mantém '{MODEL_ID_STREAM}'): ").strip()
if escolha_stream:
    if escolha_stream.isdigit() and 1 <= int(escolha_stream) <= len(modelos_disponiveis):
        MODEL_ID_STREAM = modelos_disponiveis[int(escolha_stream) - 1]
    elif escolha_stream in modelos_disponiveis:
        MODEL_ID_STREAM = escolha_stream
    else:
        raise ValueError("Modelo de stream inválido.")

print(f"✅ Modelo selecionado: {MODEL_ID}")
print(f"✅ Modelo de stream selecionado: {MODEL_ID_STREAM}")

Modelos disponíveis:
1. gemini-3-flash-preview
2. gemini-2.5-flash-lite
3. gemini-2.5-flash
4. gemini-2.5-pro
5. gemini-2.5-flash-preview
6. gemini-3.1-pro-preview
7. gemini-3.1-flash-lite-preview
✅ Modelo selecionado: gemini-3.1-flash-lite-preview
✅ Modelo de stream selecionado: gemini-3.1-flash-lite-preview

In [17]:
def gerar_resposta_stream(prompt_lote: str, caminho_md: str = "minha_resposta.md") -> None:
    response = client_stream.models.generate_content_stream(
        model=MODEL_ID_STREAM,
        contents=prompt_lote,
        config=types.GenerateContentConfig(
            #tools=[grounding_tool],
            temperature=temperature,
            system_instruction=instrucao_final,
            safety_settings=[
                types.SafetySetting(
                    category=types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                    threshold=types.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE
                )
            ]
        )
    )

    # Abre o arquivo em modo de adição ("a"). Mude para ("w") se quiser sobrescrever.
    with open(caminho_md, "a", encoding="utf-8") as arquivo_md:
        for chunk in response:
            # Exibe no console
            print(chunk.text, end="", flush=True)

            # Escreve o pedaço (chunk) no arquivo Markdown
            arquivo_md.write(chunk.text)

        # Adiciona quebras de linha ao final para separar da próxima resposta, caso use o modo "a"
        arquivo_md.write("\n\n---\n\n")

In [18]:
def gerar_resposta(prompt_lote: str, caminho_md: str = "minha_resposta_b.md") -> None:
    response = client_chat.models.generate_content(
        model= MODEL_ID,
        contents=prompt_lote,
        config=types.GenerateContentConfig(
            temperature=temperature,
            system_instruction=instrucao_final,
            safety_settings=[
                types.SafetySetting(
                    category=types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                    threshold=types.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE
                )
            ]
        )
    )

    # Exibe a resposta completa no console
    print(response.text, end="")

    # Salva a resposta completa no arquivo Markdown
    with open(caminho_md, "a", encoding="utf-8") as arquivo_md:
        arquivo_md.write(response.text)

        # Opcional: adiciona uma quebra de linha e um separador para a próxima resposta
        arquivo_md.write("\n\n---\n\n")

In [19]:


def processar_lotes(df: pd.DataFrame, num_lote: int = 5, tamanho_lote: int = 30, modo: str = 'stream', start_offset: int = 0,) -> None:
    total_lotes = num_lote
    arquivo_md = 'resposta_chat_stream.md' if modo == 'stream' else 'resposta_chat.md'
    limite_total = min(len(df), total_lotes * tamanho_lote)
    if limite_total == 0:
        raise ValueError('Nenhum ticket disponível para processamento.')
    if start_offset < 0:
        raise ValueError("start_offset deve ser >= 0")
    
    with open(arquivo_md, 'a', encoding='utf-8') as arquivo_md_saida:
        titulo = 'Respostas ITIL por Lote - Stream' if modo == 'stream' else 'Respostas ITIL por Lote - Normal'
        arquivo_md_saida.write(f'# {titulo}\n\n')
    processed_end = start_offset + limite_total
    for lote_numero in range(total_lotes):
        inicio = start_offset + lote_numero * tamanho_lote
        fim = inicio + tamanho_lote
        if inicio >= processed_end:
            print(f'Lote {lote_numero + 1}: nenhum ticket restante.')
            break

        prompt_lote = gerar_prompt_excluindo_primeiros(
            df,
            excluir=inicio,
            idioma='pt',
            quantidade=tamanho_lote,
        )

        print(f'Processando lote {lote_numero + 1}/{total_lotes} com tickets {inicio + 1} a {min(fim, processed_end)}...')
        if modo == 'stream':
            gerar_resposta_stream(prompt_lote, caminho_md=arquivo_md)
        else:
            gerar_resposta(prompt_lote, caminho_md=arquivo_md)


print('✅ Funções de lote para chat prontas.')

✅ Funções de lote para chat prontas.

In [20]:
processar_lotes(df_tickets, num_lote=5, tamanho_lote=30, modo='stream',start_offset=150)

Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 1/5 com tickets 151 a 180...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| 151 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 162 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| 182 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 183 | Gerenciamento Financeiro de Serviços | Gerenciamento de Incidentes |
| 189 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 194 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 201 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 203 | Gerenciamento Financeiro de Serviços | Gerenciamento de Incidentes |
| 205 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| 219 | Gerenciamento de Relacionamento | Análise de Negócio |
| 223 | Gerenciamento de Mudanças | Gerenciamento de Configuração de Serviço |
| 225 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| 228 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| 229 | Gerenciamento de Acessos | Gerenciamento de Incidentes |
| 230 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| 234 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 240 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 252 | Gerenciamento de Requisição de Serviço | Gerenciamento de Nível de Serviço |
| 257 | Gerenciamento de Incidentes | Gerenciamento de Nível de Serviço |
| 264 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| 279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 299 | Gerenciamento de Incidentes | Gerenciamento de Nível de Serviço |
| 301 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| 305 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Incidentes |
| 350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 356 | Gerenciamento de Requisição de Serviço | Gerenciamento de Capacidade e Desempenho |
| 364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 366 | Gerenciamento de Incidentes | Gerenciamento de Problemas |Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 2/5 com tickets 181 a 210...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| #182 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #183 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #189 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #194 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #201 | Gerenciamento de Requisição de Serviço | Gerenciamento de Incidentes |
| #203 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #205 | Gerenciamento de Requisição de Serviço | |
| #219 | Gerenciamento de Relacionamento | Análise de Negócio |
| #223 | Gerenciamento de Mudanças | Gerenciamento de Configuração de Serviço |
| #225 | Gerenciamento de Requisição de Serviço | |
| #228 | Gerenciamento de Requisição de Serviço | |
| #229 | Gerenciamento de Acessos | Gerenciamento de Incidentes |
| #230 | Gerenciamento de Catálogo de Serviço | |
| #234 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #240 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #252 | Gerenciamento de Requisição de Serviço | |
| #257 | Gerenciamento de Requisição de Serviço | Gerenciamento de Incidentes |
| #264 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #299 | Gerenciamento de Requisição de Serviço | Gerenciamento de Incidentes |
| #301 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #305 | Gerenciamento de Requisição de Serviço | |
| #331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #356 | Gerenciamento de Requisição de Serviço | |
| #364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #366 | Gerenciamento de Problemas | Gerenciamento de Mudanças |
| #372 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #376 | Gerenciamento de Requisição de Serviço | Análise de Negócio |Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 3/5 com tickets 211 a 240...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| #219 | Gerenciamento de Relacionamento | Análise de Negócio |
| #223 | Gerenciamento de Requisição de Serviço | Gerenciamento de Mudanças |
| #225 | Gerenciamento de Requisição de Serviço | |
| #228 | Gerenciamento de Requisição de Serviço | |
| #229 | Gerenciamento de Acessos | Gerenciamento de Incidentes |
| #230 | Gerenciamento de Requisição de Serviço | |
| #234 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #240 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #252 | Gerenciamento de Requisição de Serviço | |
| #257 | Gerenciamento de Incidentes | Gerenciamento de Nível de Serviço |
| #264 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #299 | Gerenciamento de Requisição de Serviço | |
| #301 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #305 | Gerenciamento de Requisição de Serviço | |
| #331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #356 | Gerenciamento de Requisição de Serviço | |
| #364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #366 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #372 | Gerenciamento de Incidentes | |
| #376 | Gerenciamento de Requisição de Serviço | Análise de Negócio |
| #398 | Gerenciamento de Incidentes | Gerenciamento de Ativos de TI |
| #403 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #405 | Gerenciamento de Requisição de Serviço | |
| #424 | Análise de Negócio | Gerenciamento de Relacionamento |
| #451 | Gerenciamento de Incidentes | Gerenciamento de Nível de Serviço |
| #452 | Gerenciamento Financeiro de Serviços | Gerenciamento de Incidentes |
| #459 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 4/5 com tickets 241 a 270...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| #252 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| #257 | Gerenciamento de Incidentes | Gerenciamento de Configuração de Serviço |
| #264 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #299 | Gerenciamento de Incidentes | Gerenciamento de Configuração de Serviço |
| #301 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #305 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| #331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #356 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| #364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #366 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #372 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #376 | Gerenciamento de Requisição de Serviço | Gerenciamento de Nível de Serviço |
| #398 | Gerenciamento de Incidentes | Gerenciamento de Configuração de Serviço |
| #403 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #405 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| #424 | Gerenciamento de Requisição de Serviço | Gerenciamento de Nível de Serviço |
| #451 | Gerenciamento de Incidentes | Gerenciamento de Configuração de Serviço |
| #452 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #459 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| #461 | Gerenciamento de Nível de Serviço | Gerenciamento Financeiro de Serviços |
| #466 | Gerenciamento de Incidentes | Gerenciamento de Configuração de Serviço |
| #468 | Gerenciamento de Incidentes | Gerenciamento de Configuração de Serviço |
| #470 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #479 | Gerenciamento Financeiro de Serviços | Gerenciamento de Nível de Serviço |
| #485 | Gerenciamento de Incidentes | Gerenciamento de Continuidade de Serviço |
| #492 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #496 | Gerenciamento de Incidentes | Gerenciamento de Problemas |Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 5/5 com tickets 271 a 300...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| #279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #299 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| #301 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| #305 | Gerenciamento de Requisição de Serviço | Gerenciamento de Configuração de Serviço |
| #331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #356 | Gerenciamento de Requisição de Serviço | Gerenciamento de Capacidade e Desempenho |
| #364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #366 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #372 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #376 | Gerenciamento de Requisição de Serviço | Gerenciamento de Nível de Serviço |
| #398 | Gerenciamento de Incidentes | Gerenciamento de Ativos de TI |
| #403 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #405 | Gerenciamento de Requisição de Serviço | Gerenciamento de Configuração de Serviço |
| #424 | Gerenciamento de Requisição de Serviço | Gerenciamento de Nível de Serviço |
| #451 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| #452 | Gerenciamento Financeiro de Serviços | Gerenciamento de Incidentes |
| #459 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| #461 | Gerenciamento de Requisição de Serviço | Gerenciamento de Capacidade e Desempenho |
| #466 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| #468 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| #470 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #479 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| #485 | Gerenciamento de Incidentes | Gerenciamento de Continuidade de Serviço |
| #492 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #496 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #504 | Gerenciamento de Incidentes | Gerenciamento de Acessos |
| #516 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| #537 | Gerenciamento de Capacidade e Desempenho | Gerenciamento de Nível de Serviço |

In [21]:
# processar_lotes(df_tickets, num_lote=5, tamanho_lote=30, modo='stream')

In [22]:
processar_lotes(df_tickets, num_lote=5, tamanho_lote=30, modo='normal',start_offset=150)

Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 1/5 com tickets 151 a 180...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| #151 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #162 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| #182 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #183 | Gerenciamento Financeiro de Serviços | Gerenciamento de Incidentes |
| #189 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #194 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #201 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #203 | Gerenciamento Financeiro de Serviços | Gerenciamento de Incidentes |
| #205 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| #219 | Gerenciamento de Relacionamento | Gerenciamento de Nível de Serviço |
| #223 | Gerenciamento de Mudanças | Gerenciamento de Configuração de Serviço |
| #225 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| #228 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| #229 | Gerenciamento de Acessos | Gerenciamento de Incidentes |
| #230 | Não há recomendação | |
| #234 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #240 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #252 | Gerenciamento de Requisição de Serviço | Gerenciamento de Nível de Serviço |
| #257 | Gerenciamento de Incidentes | Gerenciamento de Nível de Serviço |
| #264 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| #279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #299 | Gerenciamento de Incidentes | Gerenciamento de Nível de Serviço |
| #301 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| #305 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Incidentes |
| #350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #356 | Gerenciamento de Requisição de Serviço | Gerenciamento de Capacidade e Desempenho |
| #364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #366 | Gerenciamento de Incidentes | Gerenciamento de Problemas |Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 2/5 com tickets 181 a 210...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| #182 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #183 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #189 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #194 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #201 | Gerenciamento de Requisição de Serviço | Gerenciamento de Incidentes |
| #203 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #205 | Gerenciamento de Requisição de Serviço | |
| #219 | Gerenciamento de Relacionamento | Análise de Negócio |
| #223 | Gerenciamento de Mudanças | Gerenciamento de Configuração de Serviço |
| #225 | Gerenciamento de Requisição de Serviço | |
| #228 | Gerenciamento de Requisição de Serviço | |
| #229 | Gerenciamento de Acessos | Gerenciamento de Incidentes |
| #230 | Gerenciamento de Catálogo de Serviço | |
| #234 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #240 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #252 | Gerenciamento de Requisição de Serviço | |
| #257 | Gerenciamento de Requisição de Serviço | Gerenciamento de Incidentes |
| #264 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #299 | Gerenciamento de Requisição de Serviço | |
| #301 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #305 | Gerenciamento de Requisição de Serviço | |
| #331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #356 | Gerenciamento de Requisição de Serviço | |
| #364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #366 | Gerenciamento de Problemas | Gerenciamento de Mudanças |
| #372 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #376 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 3/5 com tickets 211 a 240...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| #219 | Gerenciamento de Relacionamento | Gerenciamento de Nível de Serviço |
| #223 | Gerenciamento de Requisição de Serviço | Gerenciamento de Mudanças |
| #225 | Gerenciamento de Requisição de Serviço | |
| #228 | Gerenciamento de Requisição de Serviço | |
| #229 | Gerenciamento de Incidentes | Gerenciamento de Acessos |
| #230 | Gerenciamento de Requisição de Serviço | |
| #234 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #240 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #252 | Gerenciamento de Requisição de Serviço | |
| #257 | Gerenciamento de Incidentes | Gerenciamento de Mudanças |
| #264 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #299 | Gerenciamento de Requisição de Serviço | |
| #301 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #305 | Gerenciamento de Incidentes | |
| #331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #356 | Gerenciamento de Requisição de Serviço | |
| #364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #366 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #372 | Gerenciamento de Incidentes | |
| #376 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| #398 | Gerenciamento de Incidentes | Gerenciamento de Ativos de TI |
| #403 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #405 | Gerenciamento de Requisição de Serviço | |
| #424 | Gerenciamento de Relacionamento | Gerenciamento Financeiro de Serviços |
| #451 | Gerenciamento de Incidentes | Gerenciamento de Mudanças |
| #452 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #459 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 4/5 com tickets 241 a 270...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| 252 | Gerenciamento de Requisição de Serviço | Gerenciamento de Catálogo de Serviço |
| 257 | Gerenciamento de Incidentes | Gerenciamento de Nível de Serviço |
| 264 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 299 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| 301 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| 305 | Gerenciamento de Requisição de Serviço | Gerenciamento de Configuração de Serviço |
| 331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| 350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 356 | Gerenciamento de Requisição de Serviço | Gerenciamento de Capacidade e Desempenho |
| 364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 366 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 372 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| 376 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| 398 | Gerenciamento de Incidentes | Gerenciamento de Ativos de TI |
| 403 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 405 | Gerenciamento de Requisição de Serviço | Gerenciamento de Configuração de Serviço |
| 424 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| 451 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| 452 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| 459 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| 461 | Gerenciamento Financeiro de Serviços | Gerenciamento de Capacidade e Desempenho |
| 466 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| 468 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| 470 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| 479 | Gerenciamento Financeiro de Serviços | Gerenciamento de Capacidade e Desempenho |
| 485 | Gerenciamento de Incidentes | Gerenciamento de Continuidade de Serviço |
| 492 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| 496 | Gerenciamento de Incidentes | Gerenciamento de Problemas |Sucesso! Prompt montado para um lote de 30 tickets.
Processando lote 5/5 com tickets 271 a 300...
| Ticket ID | Prática Principal | Prática Auxiliar |
| :--- | :--- | :--- |
| #279 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #294 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #299 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| #301 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| #305 | Gerenciamento de Requisição de Serviço | Gerenciamento de Configuração de Serviço |
| #331 | Gerenciamento Financeiro de Serviços | Gerenciamento de Relacionamento |
| #350 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #356 | Gerenciamento de Requisição de Serviço | Gerenciamento de Capacidade e Desempenho |
| #364 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #366 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #372 | Gerenciamento de Incidentes | Gerenciamento de Disponibilidade |
| #376 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| #398 | Gerenciamento de Incidentes | Gerenciamento de Ativos de TI |
| #403 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #405 | Gerenciamento de Requisição de Serviço | Gerenciamento de Configuração de Serviço |
| #424 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| #451 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| #452 | Gerenciamento Financeiro de Serviços | Gerenciamento de Incidentes |
| #459 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| #461 | Gerenciamento de Problemas | Gerenciamento Financeiro de Serviços |
| #466 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| #468 | Gerenciamento de Requisição de Serviço | Gerenciamento de Ativos de TI |
| #470 | Gerenciamento de Incidentes | Gerenciamento de Acessos |
| #479 | Gerenciamento Financeiro de Serviços | Gerenciamento de Capacidade e Desempenho |
| #485 | Gerenciamento de Incidentes | Gerenciamento de Continuidade de Serviço |
| #492 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #496 | Gerenciamento de Incidentes | Gerenciamento de Problemas |
| #504 | Gerenciamento de Incidentes | Gerenciamento de Acessos |
| #516 | Gerenciamento de Requisição de Serviço | Gerenciamento Financeiro de Serviços |
| #537 | Gerenciamento de Capacidade e Desempenho | Gerenciamento de Problemas |

In [23]:
# processar_lotes(df_tickets, num_lote=5, tamanho_lote=30, modo='normal')

In [24]:
# df_tickets.info()

In [25]:
# df_tickets.to_excel("amostra.xlsx", index=False)

In [26]:
# df_tickets.to_csv("amostra.csv", index=False)